var applicationModule = angular.module('qyiikApp', [ 'ui.bootstrap',
		'ui.router' ]);
applicationModule.constant('CONFIG', (function() {
	var partials = "templates/";
	return {
		PARTIALS :   partials,
	};
})());

applicationModule.config([ '$stateProvider', 'CONFIG',
		function($stateProvider, CONFIG) {
			$stateProvider.state('signin', {
				url : '/signin',
				template : '<div class="row"><div class="col-lg-12 col-md-6"><div class="panel panel-default"><div class="panel-heading"><h2>Please Sign In.</h2></div><div class="panel-body"><div class="col-lg-5"><form role="form"><fieldset><p>Enter your qyiik ID and password.</p><div class="form-group"><label for="email">qyiik ID</label><div><input id="email" name="email" type="text"placeholder="qyiik ID *" class="form-control input-md"></div></div><div class="form-group"><label for="passwordinput">Password</label><div><input id="passwordinput" name="passwordinput"type="password" placeholder="Password *"class="form-control input-md"></div></div><div class="form-group"><div class="col-lg-12 col-md-12 hidden-sm hidden-xs"><div>Forget your qyiik ID or password?</div><div><button id="submit" name="submit"class="col-lg-4 col-md-4 col-sm-8 col-xs-12 btn btn-primary pull-right">SignIn</button></div><div>Create a qyiik ID now</div></div></div><div class="hidden-lg hidden-md col-sm-12 col-xs-12"><div class="hidden-lg hidden-md col-sm-5 col-xs-12">Forgetyour qyiik ID or password?</div><div class="col-lg-1 col-md-10 col-sm-2 hidden-xs">&nbsp;</div><div class="hidden-lg hidden-md col-sm-5 col-xs-12">Createa qyiik ID now</div><div class="hidden-lg hidden-md col-sm-12 col-xs-12">&nbsp;</div><button id="submit" name="submit"class="col-lg-4 col-md-10 col-sm-5 col-xs-12 btn btn-primary">SignIn</button><div class="col-lg-1 col-md-10 col-sm-2 col-xs-12">&nbsp;</div><button id="button1id" name="button1id"class="col-lg-2 col-md-2 col-sm-5 col-xs-12 btn btn-default">Cancel</button></div><div class="row"><div class="col-lg-12 col-md-6"><div>&nbsp;</div></div></div><div class="row"><div class="col-lg-12 col-md-6"><div>&nbsp;</div></div></div></fieldset></form></div></div><div class="panel-footer"><div class="form-group hidden-sm hidden-xs"><button id="button1id" name="button1id"class="col-lg-2 col-md-4 col-sm-8 col-xs-12 btn btn-default">Cancel</button></div><div class="row"><div class="col-lg-12 col-md-6"><div>&nbsp;</div></div></div></div></div></div></div>'
			}).state('signup', {
				url : "/signup",
				template : '<div class="row"><div class="col-lg-12 col-md-6"><div class="panel panel-default"><div class="panel-heading"><h2>Searching for a talent? Create a qyiik ID.</h2></div><div class="panel-body"><div class="col-lg-5"><form role="form"><fieldset><p>A qyiik ID is your user name for everything you do onqyiik.</p><div class="form-group"><label for="selectbasic">Company</label><div><select id="selectbasic" name="selectbasic"class="form-control"><option value="1">Apple</option><option value="2">Google</option></select></div></div><div class="form-group"><label for="name">Name</label><div>Please enter your full name.</div></div><div class="form-group"><label for="firstname" style="font-weight: 400;">FirstName</label><div><input id="firstname" name="firstname" type="text"placeholder="example:jane" class="form-control input-md"></div></div><div class="form-group"><label for="lastname" style="font-weight: 400;">LastName</label><div><input id="lastname" name="lastname" type="text"placeholder="example:smith" class="form-control input-md"></div></div><div class="form-group"><label for="name">qyiik ID and Password</label><div>Enter your company email address as your qyiik id.</div></div><div class="form-group"><label for="email" style="font-weight: 400;">Email</label><div><input id="email" name="email" type="text"placeholder="example: firstlast@example.com"class="form-control input-md"></div></div><div class="form-group"><label for="passwordinput" style="font-weight: 400;">Password</label><div><input id="passwordinput" name="passwordinput" type="password"placeholder="Easy to remember, hard to guess"class="form-control input-md"></div></div><div class="form-group"><label for="confirmpassword" style="font-weight: 400;">ConfirmPassword</label><div><input id="confirmpassword" name="confirmpassword"type="password" placeholder="Enter the same password again"class="form-control input-md"></div></div><div class="form-group"><label for="checkboxes"></label><div><div class="checkbox"><label for="checkboxes-0"> <input type="checkbox"name="checkboxes" id="checkboxes-0" value="1"> I haveread and accept quiiks Terms of Use and Privacy Policy</label></div></div></div><div class="form-group"><label for="button1id"></label><div><button class="col-lg-4 col-md-10 col-sm-8 col-xs-12 btn btn-default"id="button1id" name="button1id">Cancel</button><div class="col-lg-1 col-md-10 col-sm-12 col-xs-12">&nbsp;</div><button class="col-lg-4 col-md-10 col-sm-8 col-xs-12 btn btn-primary"id="submit" name="submit">Create qyiik ID</button></div></div></fieldset></form></div></div></div></div></div>'
			}).state('security', {
				url : "/security",
				template : '<div class="row"><div class="col-lg-12 col-md-6"><div class="panel panel-default"><div class="panel-heading"><h2>Security</h2></div><div class="panel-body"><div class="col-lg-5"><form role="form"><fieldset><p>Select three security questions below. These questionswill help us verify your identity should you forget yourpassword.</p><div class="form-group"><label for="selectbasic">Security Question #1</label><div><select id="selectbasic" name="selectbasic"class="form-control"><option value="1">Apple</option><option value="2">Google</option></select></div></div><div class="form-group"><label for="firstname">Answer </label><div><input id="firstname" name="firstname" type="text"class="form-control input-md"></div></div><div class="form-group"><label for="selectbasic">Security Question #2</label><div><select id="selectbasic" name="selectbasic"class="form-control"><option value="1">Apple</option><option value="2">Google</option></select></div></div><div class="form-group"><label for="firstname">Answer </label><div><input id="firstname" name="firstname" type="text"class="form-control input-md"></div></div><div class="form-group"><label for="selectbasic">Security Question #3</label><div><select id="selectbasic" name="selectbasic"class="form-control"><option value="1">Apple</option><option value="2">Google</option></select></div></div><div class="form-group"><label for="firstname">Answer </label><div><input id="firstname" name="firstname" type="text"class="form-control input-md"></div></div></fieldset></form></div></div><div class="panel-footer"><div class="form-group"><label for="button1id"></label><div class="col-md-12"><button id="button1id" name="button1id"class="col-lg-2 col-md-5 col-sm-5 col-xs-12 btn btn-default">Cancel</button><div class="col-lg-1 col-md-1 col-sm-1 col-xs-12">&nbsp;</div><button id="submit" name="submit"class="col-lg-2 col-md-5 col-sm-5 col-xs-12 btn btn-primary">Submit</button></div></div><div class="row"><div class="col-lg-12 col-md-6"><div>&nbsp;</div></div></div><div class="row"><div class="col-lg-12 col-md-6"><div>&nbsp;</div></div></div></div></div></div></div>'
			}).state('technical', {
				url : "/technical",
				template : '<div class="row"><div class="col-lg-12 col-md-6"><div class="panel panel-default"><div class="panel-heading"><h2>Product and Technical Support</h2></div><div class="panel-body"><div class="col-lg-5"><form role="form"><fieldset><p>Contact qyiik</p><div class="form-group"><label for="firstname">Name</label><div><input id="firstname" name="firstname" type="text"placeholder="Henry Porter" class="form-control input-md"></div></div><div class="form-group"><label for="email">Email</label><div><input id="email" name="email" type="text"placeholder="henry.porter@mac.com"class="form-control input-md"></div></div><div class="form-group"><label for="lastname" >Number</label><div><input id="lastname" name="lastname" type="text"placeholder="44 7702 479594" class="form-control input-md"></div></div><div class="form-group"><label for="lastname" >Subject</label><div><input id="lastname" name="lastname" type="text" class="form-control input-md"></div></div><div class="form-group"><label for="lastname" >Message</label><div><textarea id="lastname" name="lastname" rows="10" class="form-control input-md"></textarea></div></div></fieldset></form></div></div><div class="panel-footer"><div class="form-group"><label for="button1id"></label><div class="col-md-12"><button id="button1id" name="button1id"class="col-lg-2 col-md-5 col-sm-5 col-xs-12 btn btn-default">Cancel</button><div class="col-lg-1 col-md-1 col-sm-1 col-xs-12">&nbsp;</div><button id="submit" name="submit"class="col-lg-2 col-md-5 col-sm-5 col-xs-12 btn btn-primary">Submit</button></div></div><div class="row"><div class="col-lg-12 col-md-6"><div>&nbsp;</div></div></div><div class="row"><div class="col-lg-12 col-md-6"><div>&nbsp;</div></div></div></div></div></div></div>'
			}).state('changepwd', {
				url : "/changepwd",
				template : '<div class="row"><div class="col-lg-12 col-md-6"><div class="panel panel-default"><div class="panel-heading"><h2>Change Password</h2></div><div class="panel-body"><div class="col-lg-5"><form role="form"><fieldset><div class="form-group"><label for="passwordinput">Current Password</label><div><input id="passwordinput" name="passwordinput" type="password"placeholder="Password *" class="form-control input-md"></div></div><div class="form-group"><label for="passwordinput">New Password</label><div><input id="passwordinput" name="passwordinput" type="password"placeholder="Password *" class="form-control input-md"></div></div><div class="form-group"><label for="passwordinput">Confirm Password</label><div><input id="passwordinput" name="passwordinput" type="password"placeholder="Password *" class="form-control input-md"></div></div><div class="row"><div class="col-lg-12 col-md-6"><div>&nbsp;</div></div></div><div class="row"><div class="col-lg-12 col-md-6"><div>&nbsp;</div></div></div></fieldset></form></div></div><div class="panel-footer"><div class="form-group"><label for="button1id"></label><div class="col-md-12"><button id="button1id" name="button1id"class="col-lg-2 col-md-5 col-sm-5 col-xs-12 btn btn-default">Cancel</button><div class="col-lg-1 col-md-1 col-sm-1 col-xs-12">&nbsp;</div><button id="submit" name="submit"class="col-lg-2 col-md-5 col-sm-5 col-xs-12 btn btn-primary">Submit</button></div></div><div class="row"><div class="col-lg-12 col-md-6"><div>&nbsp;</div></div></div><div class="row"><div class="col-lg-12 col-md-6"><div>&nbsp;</div></div></div></div></div></div></div>'
			});

		} ]);

applicationModule.controller('ApplicationController', function($scope, $state) {
	$scope.goTo = function(state) {
		$state.transitionTo(state);
	}

});
